// Pass the installed Playwright module path as the first argument, if needed.
const {chromium} = require(process.argv[2] || 'playwright');
const fs = require('node:fs');
(async () => {
  fs.mkdirSync('test-results', {recursive: true});
  const browser = await chromium.launch({headless: true, channel: process.env.PATCHGOBLIN_BROWSER || 'chrome'});
  const page = await browser.newPage({viewport: {width: 1580, height: 1000}});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://127.0.0.1:5051');
  await page.getByRole('heading', {name: 'Browser test project', exact: true}).waitFor();
  await page.getByRole('button', {name: 'Review the generated greeting', exact: true}).click();
  await page.getByRole('button', {name: 'Mark complete', exact: true}).waitFor();
  await page.getByLabel('Feedback or question').fill('The greeting is incorrect. Can we revise the plan to say hello?');
  await page.getByRole('button', {name: 'Send to AI planner'}).click();
  await page.getByRole('button', {name: 'Mark complete', exact: true}).waitFor({timeout: 30000});
  await page.locator('#conversation .assistant').filter({hasText: 'Fix the greeting.'}).waitFor();
  await page.screenshot({path: 'test-results/validation-discussion.png', fullPage: true});
  await page.getByRole('button', {name: 'Send back to run queue'}).click();
  await page.waitForFunction(() => (document.querySelector('#detail-content').textContent.match(/Validation/g) || []).length >= 3, {timeout: 30000});
  await page.getByRole('button', {name: 'Mark complete', exact: true}).waitFor({timeout: 30000});
  await page.getByRole('button', {name: 'Mark complete', exact: true}).click();
  await page.locator('#detail-status').filter({hasText: 'Completed'}).waitFor();
  await page.locator('#detail-dialog').getByRole('button', {name: 'Close', exact: true}).click();
  await page.getByRole('button', {name: '+ New task', exact: true}).click();
  await page.getByLabel('Task title', {exact: true}).fill('Browser test: manually plan a task');
  await page.getByLabel('Description', {exact: true}).fill('Verify manual planning and persistence.');
  await page.getByRole('button', {name: 'Save task', exact: true}).click();
  await page.getByRole('button', {name: 'Browser test: manually plan a task', exact: true}).click();
  await page.getByRole('button', {name: 'Mark planned', exact: true}).click();
  await page.locator('#detail-status').filter({hasText: 'Planned'}).waitFor();
  await page.locator('#detail-dialog').getByRole('button', {name: 'Close', exact: true}).click();
  await page.reload();
  await page.locator('[data-lane="planned"]').getByRole('button', {name: 'Browser test: manually plan a task', exact: true}).waitFor();
  await page.locator('[data-lane="completed"]').getByRole('button', {name: 'Review the generated greeting', exact: true}).waitFor();
  await page.screenshot({path: 'test-results/board-desktop.png', fullPage: true});
  await page.setViewportSize({width: 390, height: 844});
  await page.screenshot({path: 'test-results/board-mobile.png', fullPage: true});
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  if (overflow) throw new Error('Unexpected horizontal page overflow on mobile');
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('PASS: validation discussion, requeue, explicit completion, manual planning, reload persistence, mobile layout; no browser errors.');
  await browser.close();
})().catch(error => {console.error(error); process.exit(1);});
